// vue-example/src/components/MultipleChoice.vue
<template>
<div id="multiplechoice">
        <p id="Headline">In Multiple Choice</p>
        <div id="frage">
            <p>{{frage}}</p>
            <ul>
                <li v-for="(antwort) in antworten" :key="antwort" >
                    <input type="radio" name="antwort" :value="antwort" v-on:click="evaluate" /> {{ antwort }}
                </li>
            </ul>  
            {{showResult}}
        </div>
</div>
    
</template>

<script>
import Axios from 'axios';

export default {
    
    name: 'multiplechoice',
    data () { return { 
            frage : '',
            antworten : [],
            korrekt : '',
            showResult: ''
        }
    },
    methods : {
        evaluate : function (event) {
            let selectedValue = event.target.value
            if (selectedValue.startsWith(this.korrekt)){
                this.showResult = 'Antwort ist korrekt'
            } else {
                this.showResult = 'Antwort ist leider Falsch'
            }
        }
    },
    mounted () {
        Axios.get('http://localhost:8080/data.json')
            .then (res =>{
                    
                    const quest = res.data
                    this.frage = quest.frage1.frage
                    this.antworten = quest.frage1.antworten
                    this.korrekt = quest.frage1.korrekt
        })
    }
    }
</script>
<style scoped>
    #Headline{
        text-align: center;
    }
    #frage{
        text-align: left;
        padding-left: 40%;
    }
</style>

// angular-example/src/app/components/multiplechoice/multiplechoice.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';


@Component({
  selector: 'app-multiplechoice',
  template: `
    <div id="frage">
      <h2> {{ multiplechoice?.frage }} </h2>
    </div>
    <div id="antworten">
      <li *ngFor="let antwort of multiplechoice?.antworten">
           <input type="radio" [value]="antwort" (change)="evaluate(antwort)" name="antworten"/> {{ antwort }}
      </li>
      <br>
      {{ answerEvaluation }}
    </div>
   
   
  `,
  styles: [`
    #frage {
      text-align: center;
    } 
    #antworten {
      float: left;
      margin-left: 45%;
    }
    li {
      list-style-type: none;
    }

  `]
})
export class MultiplechoiceComponent implements OnInit {

   multiplechoice : Multiplechoice = null;
   answerEvaluation : string = ''

  constructor(private http: HttpClient) { }

  ngOnInit() {

    this.http.get<Multiplechoice>('http://localhost:4200/assets/data.json').subscribe(data => {
      this.multiplechoice = data['frage1']
    });

  }

  evaluate(value){
    if(value.startsWith(this.multiplechoice.korrekt)){
      this.answerEvaluation = "Anwort ist korrekt"
    } else {
      this.answerEvaluation = "Anwort ist leider falsch"
    }
    
  }
  

}
